name: mgramseva
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.3+21

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  flutter:
    sdk: flutter 

  cupertino_icons: ^1.0.2
  bluetooth_thermal_printer: ^0.0.6
  universal_html: ^2.0.8
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  datetime_picker_formfield: ^2.0.0
  horizontal_data_table: ^4.1.3
  file_picker: ^4.0.0
  http: ^0.13.3
  provider: ^6.0.0
  flutter_spinkit: ^5.0.0
  json_annotation: ^4.0.1
  url_strategy: ^0.2.0
  charset_converter: ^2.0.0
  screenshot: ^1.2.3
  number_to_words: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^4.0.0
  flutter_downloader: ^1.8.0+1
  js: ^0.6.3
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  buttons_tabbar: ^1.3.6
  url_launcher: ^6.0.9
  pin_input_text_field: ^4.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_rating_bar: ^4.0.0
  collection: ^1.15.0
  image_picker: ^0.8.4
  flutter_focus_watcher: ^2.0.0
  path: ^1.8.0
  esc_pos_utils: ^1.1.0
  new_version: ^0.2.3
  pdf: ^3.8.1
  flutter_share_me: ^1.3.0
  printing: ^5.9.1
  mime: ^1.0.1
  charts_flutter: ^0.12.0
  flutter_web_plugins:
    sdk: flutter
  firebase_analytics: ^8.3.4
  package_info_plus: ^1.3.0
  open_file: ^3.2.1       #use for web
  #open_file_safe: ^3.2.3  #use for mobiles
  syncfusion_flutter_xlsio: ^20.3.59-beta
  print_bluetooth_thermal: ^1.0.5
  nearby_connections: ^3.2.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/png/logoLancher.png"
  image_path_ios: "assets/icons/ic_launcher_apple.png"
  remove_alpha_ios: true






# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/png/
    - assets/icons/
  # To add assets to your application, add an assets section, like this:

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: HomeIcons
      fonts:
        - asset: assets/icons/fonts/HomeIcons.ttf
    - family: HomeIconsModified
      fonts:
        - asset: assets/icons/fonts/HomeIconsModified.ttf
    - family: Hindhi
      fonts:
        - asset: assets/fonts/Roboto/Hind-Regular.ttf
    - family: Punjabi
      fonts:
        - asset: assets/fonts/Roboto/punjabi.ttf
    - family: PdfIcons
      fonts:
        - asset: assets/icons/fonts/PdfIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
